### ISSUE TITLE
Addressing new failed tests 

### ISSUE THREAD

**Issue by dmohadjel** [bcgsc/orca#100]
- [x] `adoptopenjdk`: skip `brew linkage --test`
- [x] `fastqc`: install `libfontconfig1` package
- [x] `gmap-gsnap`: installing from source
- [x] `meme`: installing from source 
- [x] `mysql@5.7`: skip `brew test`
- [x] `nextgenmap`: installing from source 
- [x] `nxrepair`: removing from build
- [x] `repeatmasker`: installing from source 
- [x] `squeakr`: upgrade to latest version (https://github.com/brewsci/homebrew-bio/pull/730)
- [x] `swig`: removing this and the formula `apbspdb2pqr` which depends on it
- [x] `xssp`: upgrade to latest version (https://github.com/brewsci/homebrew-bio/pull/740)

See https://cloud.docker.com/u/bcgsc/repository/registry-1.docker.io/bcgsc/orca/builds/ba45561b-ab55-40ca-a6a0-a9da0e106934

**Comment by lcoombe** [comment]
I wouldn't be surprised if the failures of swig and links-scaffolder are related. links-scaffolder (LINKS) uses swig to build its Bloom filter module.

**Comment by dmohadjel** [comment]
```
+ brew linkage --test adoptopenjdk
Missing libraries:
libX11.so.6
libXext.so.6
libXi.so.6
libXrender.so.1
libXtst.so.6
libasound.so.2
libawt.so
libawt_xawt.so
libjava.so
libjvm.so
Unwanted system libraries:
/lib/x86_64-linux-gnu/libthread_db.so.1
/lib/x86_64-linux-gnu/libz.so.1
+ failed=1
```

**Comment by dmohadjel** [comment]
```
+ brew test fastqc
Testing fastqc
==> /home/linuxbrew/.linuxbrew/Cellar/fastqc/0.11.8/bin/fastqc test.fasta
Picked up _JAVA_OPTIONS: -Duser.home=/root/.cache/Homebrew/java_cache
Started analysis of test.fasta
Failed to process file test.fasta
java.lang.NullPointerException
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
at sun.font.SunFontManager$2.run(SunFontManager.java:431)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.SunFontManager.<init>(SunFontManager.java:376)
at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:855)
at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
at javax.swing.JComponent.print(JComponent.java:1202)
at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by dmohadjel** [comment]
```
+ brew test gmap-gsnap
Testing brewsci/bio/gmap-gsnap
==> /home/linuxbrew/.linuxbrew/Cellar/gmap-gsnap/2019-06-10/bin/gsnap --version 2>&1
Error: brewsci/bio/gmap-gsnap: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <0> expected but was
<255>.
```

**Comment by dmohadjel** [comment]
```
+ brew test links-scaffolder
Testing brewsci/bio/links-scaffolder
==> /home/linuxbrew/.linuxbrew/Cellar/links-scaffolder/1.8.7/bin/LINKS
Error: Missing mandatory options -f and -s.
```

**Comment by dmohadjel** [comment]
```
+ brew test meme
Testing brewsci/bio/meme
==> /home/linuxbrew/.linuxbrew/Cellar/meme/5.0.4/bin/meme /home/linuxbrew/.linuxbrew/Cellar/meme/5.0.4/tests/common/At.s
Last 15 lines from /root/.cache/Homebrew/Logs/meme/test.01.meme:
SEQUENCE GROUP USAGE-- Starts/EM: p0; Trim: p0; pvalue: p0; nsites: p0,p1,p2
SEEDS: maxwords 10133 highwater mark: seq 19 pos 475
Initializing the motif probability tables for 2 to 19 sites...
nsites = 2 nsites = 3 nsites = 4 nsites = 5 nsites = 6 nsites = 7 nsites = 8 nsites = 9 nsites = 10 nsites = 11 nsites = 12 nsites = 13 nsites = 14 nsites = 15 nsites = 16 nsites = 17 nsites = 18 nsites = 19
Done initializing.
seqs= 19, min_w= 275, max_w= 1112, total_size= 10133
motif=1
SEED DEPTHS: 2 4 8 16 19
SEED WIDTHS: 8 11 15 21 29 41 50
starts: w=8, seq=0, l=407 starts: w=8, seq=5, l=472 starts: w=8, seq=10, l=339 starts: w=8, seq=15, l=500 starts: w=11, seq=0, l=407 starts: w=11, seq=5, l=472 starts: w=11, seq=10, l=339 starts: w=11, seq=15, l=500 starts: w=15, seq=0, l=407 starts: w=15, seq=5, l=472 starts: w=15, seq=10, l=339 starts: w=15, seq=15, l=500 starts: w=21, seq=0, l=407 starts: w=21, seq=5, l=472 starts: w=21, seq=10, l=339 starts: w=21, seq=15, l=500 starts: w=29, seq=0, l=407 starts: w=29, seq=5, l=472 starts: w=29, seq=10, l=339 starts: w=29, seq=15, l=500 starts: w=41, seq=0, l=407 starts: w=41, seq=5, l=472 starts: w=41, seq=10, l=339 starts: w=41, seq=15, l=500 starts: w=50, seq=0, l=407 starts: w=50, seq=5, l=472 starts: w=50, seq=10, l=339 starts: w=50, seq=15, l=500 em: w= 8, psites= 2, iter= 0 em: w= 8, psites= 4, iter= 0 em: w= 8, psites= 8, iter= 0 em: w= 8, psites= 16, iter= 0 em: w= 8, psites= 19, iter= 0 em: w= 11, psites= 2, iter= 0 em: w= 11, psites= 4, iter= 0 em: w= 11, psites= 8, iter= 0 em: w= 11, psites= 16, iter= 0 em: w= 11, psites= 19, iter= 0 em: w= 15, psites= 2, iter= 0 em: w= 15, psites= 2, iter= 10 em: w= 15, psites= 4, iter= 0 em: w= 15, psites= 8, iter= 0 em: w= 15, psites= 16, iter= 0 em: w= 15, psites= 19, iter= 0 em: w= 21, psites= 2, iter= 0 em: w= 21, psites= 4, iter= 0 em: w= 21, psites= 8, iter= 0 em: w= 21, psites= 16, iter= 0 em: w= 21, psites= 19, iter= 0 em: w= 21, psites= 19, iter= 10 em: w= 29, psites= 2, iter= 0 em: w= 29, psites= 4, iter= 0 em: w= 29, psites= 8, iter= 0 em: w= 29, psites= 8, iter= 10 em: w= 29, psites= 16, iter= 0 em: w= 29, psites= 16, iter= 10 em: w= 29, psites= 19, iter= 0 em: w= 41, psites= 2, iter= 0 em: w= 41, psites= 4, iter= 0 em: w= 41, psites= 4, iter= 10 em: w= 41, psites= 4, iter= 20 em: w= 41, psites= 4, iter= 30 em: w= 41, psites= 8, iter= 0 em: w= 41, psites= 16, iter= 0 em: w= 41, psites= 16, iter= 10 em: w= 41, psites= 19, iter= 0 em: w= 50, psites= 2, iter= 0 em: w= 50, psites= 4, iter= 0 em: w= 50, psites= 4, iter= 10 em: w= 50, psites= 8, iter= 0 em: w= 50, psites= 16, iter= 0 em: w= 50, psites= 19, iter= 0 Warning: Cannot convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.
Expat.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
Warning: meme_xml_to_html exited abnormally and may have failed to create HTML output.
Error: brewsci/bio/meme: failed
Failed executing:
```

**Comment by dmohadjel** [comment]
```
+ brew test mysql@5.7
Testing mysql@5.7
==> /home/linuxbrew/.linuxbrew/Cellar/mysql@5.7/5.7.27/bin/mysqld --initialize-insecure --user=root --basedir=/home/linuxbrew/.linuxbrew/Cellar/mysql@5.7/5.7.27 --datadir=/tmp/d20190822-28697-1t1u0uq --tmpdir=/tmp/d20190822-28697-1t1u0uq
2019-08-22T00:40:50.094363Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2019-08-22T00:40:50.094503Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
2019-08-22T00:40:50.094535Z 0 [Note] /home/linuxbrew/.linuxbrew/Cellar/mysql@5.7/5.7.27/bin/mysqld (mysqld 5.7.27) starting as process 28735 ...
2019-08-22T00:40:50.097964Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2019-08-22T00:40:50.108123Z 0 [ERROR] Aborting
2019-08-22T00:40:50.108398Z 0 [Note] Binlog end
2019-08-22T00:40:50.108784Z 0 [Note] /home/linuxbrew/.linuxbrew/Cellar/mysql@5.7/5.7.27/bin/mysqld: Shutdown complete
==> curl 127.0.0.1:3306
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (7) Failed to connect to 127.0.0.1 port 3306: Connection refused
Error: mysql@5.7: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

**Comment by dmohadjel** [comment]
```
+ brew test nextgenmap
+ tee test.log
Testing brewsci/bio/nextgenmap
==> /home/linuxbrew/.linuxbrew/Cellar/nextgenmap/0.5.5/bin/ngm -h 2>&1
Error: brewsci/bio/nextgenmap: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <1> expected but was
<127>.
```

**Comment by dmohadjel** [comment]
```
+ brew test nxrepair
Testing brewsci/bio/nxrepair
==> /home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/bin/nxrepair --help
Traceback (most recent call last):
File "/home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/bin/nxrepair", line 11, in <module>
load_entry_point('nxrepair==0.13', 'console_scripts', 'nxrepair')()
File "/home/linuxbrew/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/linuxbrew/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
return ep.load()
File "/home/linuxbrew/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
return self.resolve()
File "/home/linuxbrew/.linuxbrew/opt/python@2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/home/linuxbrew/.linuxbrew/opt/python@2/lib/python2.7/site-packages/nxrepair/nxrepair.py", line 31, in <module>
import matplotlib.pyplot as plt
File "/home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
import matplotlib.colorbar
File "/home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/lib/python2.7/site-packages/matplotlib/colorbar.py", line 38, in <module>
import matplotlib.gridspec as gridspec
File "/home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/lib/python2.7/site-packages/matplotlib/gridspec.py", line 29, in <module>
import matplotlib._layoutbox as layoutbox
File "/home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/lib/python2.7/site-packages/matplotlib/_layoutbox.py", line 23, in <module>
import kiwisolver as kiwi
ImportError: /home/linuxbrew/.linuxbrew/Cellar/nxrepair/0.13_1/libexec/lib/python2.7/site-packages/kiwisolver.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE, version CXXABI_1.3
Error: brewsci/bio/nxrepair: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by dmohadjel** [comment]
```
+ brew test repeatmasker
Testing brewsci/bio/repeatmasker
==> /home/linuxbrew/.linuxbrew/Cellar/repeatmasker/4.0.7_4/bin/RepeatMasker
Soundex.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
Error: brewsci/bio/repeatmasker: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by dmohadjel** [comment]
```
+ brew linkage --test squeakr
Missing libraries:
libboost_thread-mt.so.1.69.0
+ failed=1
```

```
+ brew test squeakr
Testing brewsci/bio/squeakr
==> /home/linuxbrew/.linuxbrew/Cellar/squeakr/0.5_2/bin/squeakr-count -h 2>&1
Error: brewsci/bio/squeakr: failed
An exception occurred within a child process:
Test::Unit::AssertionFailedError: <0> expected but was
<127>.
```

**Comment by dmohadjel** [comment]
```
+ brew test swig
Testing swig
==> /home/linuxbrew/.linuxbrew/Cellar/swig/4.0.0/bin/swig -ruby test.i
==> /home/linuxbrew/.linuxbrew/bin/gcc -c -fPIC test.c
==> /home/linuxbrew/.linuxbrew/bin/gcc -c -fPIC test_wrap.c -I/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0 -I/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/include/ruby-2.3.0/x86_64-linux
==> /home/linuxbrew/.linuxbrew/bin/gcc -shared test.o test_wrap.o -o test.so -Wl,-rpath,/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib -lruby-static
Last 15 lines from /root/.cache/Homebrew/Logs/swig/test.04.gcc:
2019-08-22 00:59:15 +0000
/home/linuxbrew/.linuxbrew/bin/gcc
-shared
test.o
test_wrap.o
-o
test.so
-Wl,-rpath,/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib
-lruby-static
/usr/bin/ld: cannot find -lruby-static
collect2: error: ld returned 1 exit status
Error: swig: failed
```

**Comment by dmohadjel** [comment]
```
+ brew linkage --test xssp
Missing libraries:
libboost_filesystem.so.1.69.0
libboost_iostreams-mt.so.1.69.0
libboost_program_options-mt.so.1.69.0
libboost_regex-mt.so.1.69.0
libboost_thread-mt.so.1.69.0
libboost_timer.so.1.69.0
libboost_unit_test_framework-mt.so.1.69.0
+ failed=1
```

```
+ brew test xssp
Testing brewsci/bio/xssp
==> Downloading https://files.rcsb.org/download/3ZZZ.pdb.gz
==> /home/linuxbrew/.linuxbrew/Cellar/xssp/3.0.5_1/bin/mkdssp -i 3zzz.pdb -o /tmp/xssp-test-20190822-10465-11vyofx/test.dssp
Last 15 lines from /root/.cache/Homebrew/Logs/xssp/test.01.mkdssp:
2019-08-22 01:03:44 +0000
/home/linuxbrew/.linuxbrew/Cellar/xssp/3.0.5_1/bin/mkdssp
-i
3zzz.pdb
-o
/tmp/xssp-test-20190822-10465-11vyofx/test.dssp
/home/linuxbrew/.linuxbrew/Cellar/xssp/3.0.5_1/bin/mkdssp: error while loading shared libraries: libboost_iostreams-mt.so.1.69.0: cannot open shared object file: No such file or directory
Error: brewsci/bio/xssp: failed
```
