### ISSUE TITLE
poretools

### ISSUE THREAD

**Issue by tmozgach** [bcgsc/orca#21]
``` ==> Installing homebrew/science/poretools
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/arq5x/poretools/archive/v0.6.0.tar.gz
==> Downloading from https://codeload.github.com/arq5x/poretools/tar.gz/v0.6.0
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/c6/fe/97319581905de40f1be7015a0ea1bd336a756f6249914b148a17eefa75dc/Cython-0.24.1.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/poretools-20170816-16741-dgiq70/poretools-0.6.0/cython --single-version-externally-managed --record=in
^[[B==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/poretools--homebrew-virtualenv-20170816-16741-1t5oaul/target --single-version-externally-managed --rec
==> python -s /tmp/poretools--homebrew-virtualenv-20170816-16741-1t5oaul/target/bin/virtualenv -p python /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec
==> Downloading https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/poretools--six-20170816-16741-1iaz3u2/
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.tar.gz
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/poretools--numpy-20170816-16741-1ixkh4
==> Downloading https://files.pythonhosted.org/packages/c2/4b/137dea450d6e1e3d474e1d873cd1d4f7d3beed7e0dc973b06e8e10d32488/cycler-0.10.0.tar.gz
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/poretools--Cycler-20170816-16741-5wuk3
==> Downloading https://files.pythonhosted.org/packages/22/82/64dada5382a60471f85f16eb7d01cc1a9620aea855cd665609adf6fdbb0d/h5py-2.6.0.tar.gz
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/poretools--h5py-20170816-16741-1ib5exy
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/poretools/07.pip:
  Removing source in /tmp/pip-TW4Pws-build
Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-TW4Pws-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-BN20bc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/h5py" failed with error code 1 in /tmp/pip-TW4Pws-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-TW4Pws-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-BN20bc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/h5py" failed with error code 1 in /tmp/pip-TW4Pws-build/

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
poretools: Build a bottle for Linuxbrew: h5py: cc: error: unrecognized command line option '-R' https://github.com/Homebrew/homebrew-science/pull/5065 ```

**Comment by sjackman** [comment]
It's failing during `pip install h5py`.
Please report the output of…
```
brew install poretools
brew gist-logs poretools
pip install h5py
```

**Comment by tmozgach** [comment]
@sjackman  here you are:
```
==> Installing poretools from homebrew/science
==> Installing dependencies for homebrew/science/poretools: pkg-config, szip, hdf5
==> Installing homebrew/science/poretools dependency: pkg-config
==> Downloading https://linuxbrew.bintray.com/bottles/pkg-config-0.29.2_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring pkg-config-0.29.2_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2_1: 11 files, 1.8MB
==> Installing homebrew/science/poretools dependency: szip
==> Downloading https://linuxbrew.bintray.com/bottles/szip-2.1.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring szip-2.1.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/szip/2.1: 11 files, 123.8KB
==> Installing homebrew/science/poretools dependency: hdf5
==> Downloading https://linuxbrew.bintray.com/bottles/hdf5-1.10.1_2.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring hdf5-1.10.1_2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/hdf5/1.10.1_2: 275 files, 20.3MB
==> Installing homebrew/science/poretools
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/arq5x/poretools/archive/v0.6.0.tar.gz
==> Downloading from https://codeload.github.com/arq5x/poretools/tar.gz/v0.6.0
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/c6/fe/97319581905de40f1be7015a0ea1bd336a756f6249914b148a17eefa75dc/Cython-0.24.1.
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/poretools-20170818-24541-2srzfz/poretools-0.6.0/cython --single-ve
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/poretools--homebrew-virtualenv-20170818-24541-37at7w/target --sing
==> python -s /tmp/poretools--homebrew-virtualenv-20170818-24541-37at7w/target/bin/virtualenv -p python /home/linuxbrew/.linuxbrew/Cellar
==> Downloading https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb18/numpy-1.11.1.t
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/c2/4b/137dea450d6e1e3d474e1d873cd1d4f7d3beed7e0dc973b06e8e10d32488/cycler-0.10.0.
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/22/82/64dada5382a60471f85f16eb7d01cc1a9620aea855cd665609adf6fdbb0d/h5py-2.6.0.tar
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/15/89/240b4ebcd63bcdde9aa522fbd2e13f0af3347bea443cb8ad111e3b4c6f3a/matplotlib-1.5
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/11/09/e66eb844daba8680ddff26335d5b4fead77f60f957678243549a8dd4830d/pandas-0.18.1.
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/65/25/1bb68622ca70abc145ac9c9bcd0e837fccd2889d79cee641aa8604d18a11/pyparsing-2.1.
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/3e/f5/aad82824b369332a676a90a8c0d1e608b17e740bbb6aeeebca726f17b902/python-dateuti
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/f7/c7/08e54702c74baf9d8f92d0bc331ecabf6d66a56f6d36370f0a672fc6a535/pytz-2016.6.1.
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
==> Downloading https://files.pythonhosted.org/packages/01/a1/dce70d47377d662aa4b0895df8431aee92cea6faefaab9dae21b0f901ded/scipy-0.18.0.t
######################################################################## 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/po
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/poretools/13.pip:
  Removing source in /tmp/pip-UAD8_O-build
Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-UAD8_O-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-z0vhi2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-UAD8_O-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-UAD8_O-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-z0vhi2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-UAD8_O-build/

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

These open issues may also help:
poretools: Build a bottle for Linuxbrew: h5py: cc: error: unrecognized command line option '-R' https://github.com/Homebrew/homebrew-science/pull/5065
```
```
https://gist.github.com/e14098944db6e6433666506db1f99690
```
```
pip2 install h5py
Collecting h5py
  Downloading h5py-2.7.0-cp27-cp27m-manylinux1_x86_64.whl (4.3MB)
    100% |################################| 4.4MB 94kB/s 
Requirement already satisfied: six in ./.linuxbrew/Cellar/matplotlib/2.0.2/libexec/lib/python2.7/site-packages (from h5py)
Requirement already satisfied: numpy>=1.7 in ./.linuxbrew/lib/python2.7/site-packages (from h5py)
Installing collected packages: h5py
Successfully installed h5py-2.7.0
```

**Comment by sjackman** [comment]
This time it failed while installing the vendored copy `scipy`. Try removing the vendored copies of `numpy` and `scipy` and using instead `depends_on "numpy"` and `depends_on "scipy"`.

**Comment by tmozgach** [comment]
@sjackman I got the following error again:
```
==> /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/poretools--h5py-20170821-2668-10qk2uq/h5py-2.6.0
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/poretools/06.pip:
  Removing source in /tmp/pip-fhAzvS-build
Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fhAzvS-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ijJkjn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/h5py" failed with error code 1 in /tmp/pip-fhAzvS-build/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fhAzvS-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ijJkjn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/poretools/0.6.0_5/libexec/include/site/python2.7/h5py" failed with error code 1 in /tmp/pip-fhAzvS-build/
```

**Comment by sjackman** [comment]
I've run into that `h5py` issue before over at https://github.com/Homebrew/homebrew-science/pull/5065
Can you troubleshoot this issue? Does `pip install h5py` work interactively?

**Comment by tmozgach** [comment]
works in the empty container
