### ISSUE TITLE
Formulae fail after updating boost, linuxbrew

### ISSUE THREAD

**Issue by tmozgach** [bcgsc/orca#25]
Install:

- [ ] sga

Test:

- [ ] circlator
- [ ] discovar
- [ ] express
- [ ] kat
- [ ] mapsembler2
- [ ] mummer
- [ ] poretools
- [ ] repeatmasker
- [ ] sdsl-lite

**Comment by tmozgach** [comment]
`matplotlib` is probably responsible for errors (poretools).

**Comment by tmozgach** [comment]
- [ ] discovar 4.9
- [ ] kat 4.9
- [ ] lrsim - perl, solved
- [ ] mapsembler2 4.9
- [ ] mummer not perl.
- [ ] poretools not perl
- [ ] repeatmasker not perl
- [ ] sdsl-lite 4.9

**Comment by sjackman** [comment]
> sga works in empty image =>something influences on it

What's the error message?

**Comment by sjackman** [comment]
> mummer works in empty image =>something influences on it

That's the version of `perl` I believe. It doesn't like newer versions of Perl.

**Comment by sjackman** [comment]
> poretools works in empty image =>something influences on it

The error message is from `h5py`. See if you can get a more helpful and verbose error message from `brew gist-logs poretools`

**Comment by tmozgach** [comment]
in the formulae `discovar` there is ``` fails_with :gcc => "5" do
    cause "error: reference to 'align' is ambiguous. See https://groups.google.com/a/broadinstitute.org/forum/?hl=en&fromgroups=#!topic/discovar-user-forum/zuqNcaRUetA"
end ```
So, fixing will be tricky?

**Comment by sjackman** [comment]
`discovar` shouldn't need a fix. Is `brew test discovar` failing? What's the error message?

**Comment by sjackman** [comment]
Oh, you mean `brew install discovar` is failing. In that case, add
```ruby
depends_on "gcc@4.9" => :build
```

**Comment by sjackman** [comment]
No need to bump the revision for `discovar`. `brew install discovar` should use the bottle and should succeed. What command is failing, and what is the error message?

**Comment by tmozgach** [comment]
`discovar` fails a test. If I compile that with 4.9, it works, but in my image there is no 4.9 and you said that it should work with 5 otherwise it is a bug.

**Comment by sjackman** [comment]
`brew install discovar` should use the precompiled bottle and succeed. `brew test discovar` should succeed with `gcc-5` (I think). Which command is failing, and what is the error message?

**Comment by tmozgach** [comment]
linuxbrew@13b6730f2934:~$ brew test discovar
```
Testing homebrew/science/discovar
Error: homebrew/science/discovar: failed
homebrew/science/discovar cannot be built with any available compilers.
Install Clang or brew install gcc
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/compilers.rb:127:in `compiler'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/compilers.rb:109:in `select_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV/shared.rb:176:in `compiler'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV/std.rb:78:in `setup_build_environment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:22:in `<main>'
```

**Comment by tmozgach** [comment]
linuxbrew@13b6730f2934:~$ which gcc
/home/linuxbrew/.linuxbrew/bin/gcc

**Comment by sjackman** [comment]
Okay. Good to know. That's kind of a bug in `brew test`, sort of. It'd be tricky to fix though. If you add `gcc@4.9` to the ORCA image it should work.

**Comment by tmozgach** [comment]
Just instaliing gcc@4.9 works!

**Comment by tmozgach** [comment]
2017.10.12
Install:
- [ ] kent-tools

**Comment by sjackman** [comment]
What's the error message?

**Comment by tmozgach** [comment]
@sjackman 

```
[91mcurl: (23) Failed writing body (9776 != 16160)
[0m
[91mError: Failed to download resource "kent-tools"
Download failed: https://linuxbrew.bintray.com/bottles-science/kent-tools-353.x86_64_linux.bottle.tar.gz
[0m
[91mWarning: Bottle installation failed: building from source.[0m
[91m
[0m
[91mError: No space left on device @ dir_s_mkdir - /tmp/homebrew20171013-5-19ydkj3
[0m
Removing intermediate container 011074aec7b9
```

**Comment by sjackman** [comment]
> No space left on device

The disk is full.
