### ISSUE TITLE
Broken Tools 

### ISSUE THREAD

**Issue by suujia** [bcgsc/orca#63]
- [ ] abricate
`XS.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
The post-install step did not complete successfully`

- [ ] atram
`contains conflicting version recursive dependencies: isl, isl@0.18, gcc@6, gcc (error: fails on linuxbrew/linuxbrew image as well as dockerhub) 
`
- [ ] bandage
`dependency on pulseaudio, which is broken shown in PR: [pulseaudio: Build a bottle for Linuxbrew](https://github.com/Linuxbrew/homebrew-core/pull/8429)
`

- [ ] berkeley-db
`Warning: libproxy dependency berkeley-db was built with a different C++ standard -- library (libstdc++ from gcc-5). This may cause problems at runtime.  (only warning, no build error) 
`

- [ ] 

- [ ]

**Comment by sjackman** [comment]
```
XS.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080) The post-install step did not complete successfully
```

@tseemann Does the `abricate` bottle need to be updated?

**Comment by sjackman** [comment]
We can drop `atram` from ORCA.

I'd prefer to keep `bandage` in ORCA if possible, but we can drop it if necessary.

The `phylip` and `exabayes` conflict is unfortunate. I've opened an issue upstream at https://github.com/aberer/exabayes/issues/7

`express` is in the legacy repo Brewsci/science. I'm okay with removing it from ORCA.

`trinity` is also in the legacy repo Brewsci/science. We can drop it if necessary.

**Comment by suujia** [comment]
#### Python3.6 dependency (we have python3.7) 

`1. Missing libraries:  libpython3.6m.so.1.0`
- [ ] brew linkage --test anvio
- [ ] brew linkage --test circlator
- [ ] brew linkage --test cutadapt
- [ ] brew linkage --test iva
- [ ] brew linkage --test kat
- [ ] brew linkage --test matplotlib
- [ ] brew linkage --test portcullis
- [ ] brew linkage --test tigmint

#### Other linkage fails 
`2. Unwanted system libraries:  libanl.so.1`
- [ ] brew linkage --test emacs

`3. Missing libraries:  libmysqlclient.so.20`
- [ ] brew linkage --test kent-tools

`4. Unwanted system libraries:  libidn.so.11`
- [ ] brew linkage --test magic-blast
- [ ] brew linkage --test tbl2asn

`5. Missing libraries:  libdb-6.2.so`
- [ ] brew linkage --test swi-prolog


## Test fails 

- [ ] beast
`Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path`

- [ ] bioperl
`<0> expected but was <126>.`

- [ ] busco
` ModuleNotFoundError: No module named 'pipebricks'`

- [ ] cerulean
`ImportError: No module named kiwisolver`

- [ ] circos
`Clone.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)`

- [ ] exabayes
** Error noted in above comment; 

- [ ] lrsim
`<2> expected but was <1>.`

- [ ] mysql
` Failed to connect to 127.0.0.1 port 3306: Connection refused`

- [ ] nanopolish
`<0> expected but was<134>.`

- [ ] nlopt
`collect2: error: ld returned 1 exit status`

- [ ] porechop
`No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/porechop/0.2.3/bin/porechop`

- [ ] ropebwt2
`<1> expected but was<0>.`

- [ ] tigmint      & (found above -  python3.6)
`ModuleNotFoundError: No module named 'pybedtools.cbedtools'`


#### Broken Perl dependency 
- [ ] maker
`/perl/5.26.1_1/bin/perl: bad interpreter: No such file or directory`

- [ ] mlst
`XS.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)`

- [ ] repeatmasker
`Soundex.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)`

#### Broken ruby dependency 
- [ ] ruby
`An error occurred while installing gemoji (3.0.0), and Bundler cannot continue.`

- [ ] idba
`execution expired`

- [ ] pigz
`/ruby/2.3.0/timeout.rb:106:in `timeout'`

- [ ] raxml-ng
`timeout.rb:106:in `timeout'`

- [ ] treepl
`ruby/2.3.0/timeout.rb:106:in `timeout'`

- [ ] unicycler
ruby/2.3.0/timeout.rb:106:in `timeout'

**Comment by tseemann** [comment]
@sjackman I'm guessing anything related to perl XS (compiled C bits) would have broken during the move to Perl 5.26 ?

**Comment by sjackman** [comment]
I believe you mean the move to Perl 5.28, and yes, that appears to be the case. Rebuilding the bottles by bumping the revision should solve the issue.

**Comment by sjackman** [comment]
@suujia The same issue seems to affect the Python 3.6 to 3.7 migration. Could you please open a PR to bump the revision of each formula that has the `Missing libraries: libpython3.6m.so.1.0` issue?

**Comment by suujia** [comment]
#### Fixing libpython3.6m.so.1.0 dependencies 
Fixes: `Missing libraries: libpython3.6m.so.1.0`

##### Anvio 
Anvio seems to be hosted [here](https://github.com/brewsci/homebrew-science/blob/master/Formula/anvio.rb), and was last maintained in July. Should we just use their formula instead of the homebrew/science formula? 

##### circlator
-migrate from science https://github.com/brewsci/homebrew-bio/pull/351

cutadapt
-migrate from science https://github.com/brewsci/homebrew-bio/pull/352
python issue 

iva
-migrate from science --> python issue locally

##### kat & matplotlib
Warning: Bottle installation failed: building from source. 
--> I checked that the sha256 were correct for the two bottles (linux & sierra). Building from source works perfectly though. (aside from: `brewsci/bio/kat dependency gmp was built with a different C++ standard library (libstdc++ from gcc-5)`) 

Python 3.7 problem rebuild fixed by PR: https://github.com/brewsci/homebrew-bio/pull/350

##### portcullis
Works good locally, will make PR

##### tigmint
still fails linkage test after reinstall/bumping revision

**Comment by sjackman** [comment]
**anvio**: Let's either migrate the formula to Brewsci/bio or remove it from ORCA.

`Warning: Bottle installation failed: building from source.` Odd. Do you see that error locally? Is it `matplotlib` or `kat` giving that error?

**Comment by sjackman** [comment]
**tigmint** Reinstalling from source should resolve this issue.

**Comment by suujia** [comment]
**anvio** I'm migrating this as well, updating all the downloads in this file. But the error message I get is:  I've done depends_on "hdf5" then a resource download on h5py.
```
Command "/home/linuxbrew/.linuxbrew/Cellar/anvio/5.1/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-7x_0idzs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fqlkqi23/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/anvio/5.1/libexec/include/site/python3.7/h5py" failed with error code 1 in /tmp/pip-req-build-7x_0idzs/
```
**mysql** 
I received the same error on orca image with brew test. Reinstalled dependency openssl, then reinstalling mysql didn't work. Although a fresh install of mysql in linuxbrew/linuxbrew image connects perfectly. There was a recent commit in homebrew-core on mysql, and our beginning of our docker build was from 1 month ago, so I will try to rebuild. 

**busco** Similar issue: https://gitlab.com/ezlab/busco/issues/27

**ruby tools:** timeout tools are ignored

**Comment by sjackman** [comment]
We can drop `anvio` if necessary. Both `mysql` and `busco` are pretty critical. Focus your efforts on those.

**Comment by suujia** [comment]
**beast** 
https://francoismichonneau.net/2014/05/how-to-install-beagle-on-ubuntu/
```
If you don’t have root privileges and need to install BEAGLE somewhere else 
(let’s say your home directory using ./configure --prefix=$HOME), then you 
need to edit the beast executable to include this path in the java.library.path. 
In our example the library will be installed in $HOME/lib, which means that in 
the executable, this -Djava.library.path="$BEAST_LIB:/usr/local/lib" needs to 
be changed to -Djava.library.path="$BEAST_LIB:/usr/local/lib:$HOME/lib". 
Otherwise, you are going to see this message:

Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path BEAGLE not installed/found
```
but I cant seem to find `-Djava.library.path` or `BEAST_LIB`

**nlopt** 
```
/home/linuxbrew/.linuxbrew/lib/libnlopt.a(local.o):/tmp/nlopt-20170821-63567-15t7vdf/nlopt-2.4.2/stogo/linalg.h:36: more undefined references to `operator delete[](void*)' follow
/home/linuxbrew/.linuxbrew/lib/libnlopt.a(local.o): In function `_GLOBAL__sub_I_local.cc':
/usr/include/c++/4.8/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/usr/include/c++/4.8/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
```

**Comment by sjackman** [comment]
I fixed the `brew test nlopt` issue with PR https://github.com/Linuxbrew/homebrew-core/pull/8979

**Comment by sjackman** [comment]
To fix `beast`, try adding…
```ruby
inreplace bin/"beast", "/usr/local/lib:$LD_LIBRARY_PATH", Formula["beagle"].lib
```

**Comment by suujia** [comment]
Regarding the linkage failures: 

#### emacs
Unwanted system libraries: libanl.so.1
https://github.com/brewsci/homebrew-bio/pull/211
From this issue it looks like its an zlib problem , I added it as a dependency

#### magic-blast  &  tbl2asn
https://github.com/brewsci/homebrew-science/blob/275f69160a5a41a6ae0c517f2f47af91f57b5990/tbl2asn.rb
https://github.com/brewsci/homebrew-bio/blob/3e1a326353e8efbe75a6c473157d25d7fd7343fd/Formula/magic-blast.rb
Unwanted system libraries: libidn.so.11
hmmm I tried uninstalling libidn, removing libidn dependency, reinstalling libidn. Not sure how to fix this one. I understand that libidn is required for linux. Both require zlib though, not sure if that broke it. 

#### swi-prolog
Missing libraries: libdb-6.2.so
this also has a dependency on zlib

**Comment by sjackman** [comment]
```
$ brew list libidn | grep -F libidn.so.
/home/linuxbrew/.linuxbrew/Cellar/libidn/1.35/lib/libidn.so.12
/home/linuxbrew/.linuxbrew/Cellar/libidn/1.35/lib/libidn.so.12.6.0
```
`libidn` bumped their SONAME (shared object library version) from 11 to 12.

Normally rebuilding the bottle (recompiling these from source) would fix this problem. Both of these tools however use binary upstream packages, meaning they're not built from source.

Since the system provides these libraries, it will work, so for now for ORCA, I suggest we ignore these two warnings by adding them to this list `emacs|magic-blast|tbl2asn`:
https://github.com/bcgsc/orca/blob/7b7c0ed54759e050e682aaf191ed35b34eb96b26/docker.test.yml#L11

Another possible fix is to modify the executable to change the dependency from `libidn.so.11` to `libidn.so.12`. See for example https://github.com/brewsci/homebrew-bio/blob/2106f2e4af5a30911ef5ab9289660832c3b9715f/Formula/mir-prefer.rb#L37

Another possible fix is to package an older version of `libidn` that provides `libidn.so.11` for Brewsci/bio.

Another possible fix is to build these two packages from source rather than using upstream binaries.

**Comment by sjackman** [comment]
```
brew linkage swi-prolog
Missing libraries: libdb-6.2.so
```
`brew test swi-prolog` succeeds, so let's add `swi-prolog` to the list of ignored errors.

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/824, which should fix `emacs` (after `brew update`).

**Comment by suujia** [comment]
[The latest docker build: ](https://hub.docker.com/r/bcgsc/orca/builds/bc3ho4gpkxfcowekh3nwtr4/)
#### 1. brew linkage --test dextractor
   Missing libraries: libhdf5.so.101
brew test dextractor <1> expected but was<127>.
#### brew linkage --test phyx
Unwanted system libraries: libmvec.so.1

#### 2. brew test isl@0.18
test.c:1:21: fatal error: isl/ctx.h: No such file or directory compilation terminated.
#### 3. brew test meme
```
 Warning: Can not convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.
Expat.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
```
#### 4. brew test ropebwt2
<1> expected but was <0>.
#### 5. brew test ruby
```
Bundler::GemspecError: Could not read gem at
/tmp/ruby-test-20180831-5735-1mc72o7/cache/gemoji-3.0.0.gem. It may be corrupted.
An error occurred while installing gemoji (3.0.0), and Bundler cannot continue.
Make sure that `gem install gemoji -v '3.0.0'` succeeds before bundling.
```
## Bioperl

#### brew test bioperl
==> bp_biogetseq.pl -h </dev/null 2>&1
Error: brewsci/bio/bioperl: failed
<0> expected but was <126>.
#### brew test circos
Clone.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
Error: brewsci/bio/circos: failed
#### brew test repeatmasker
Soundex.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080)
<0> expected but was <1>.

## Java  (Both depends on java 1.8) 

#### brew test igv
Picked up _JAVA_OPTIONS:  -Duser.home=/home/linuxbrew/.cache/Homebrew/java_cache
<0> expected but was <1>.

#### brew test apache-spark
```
Picked up _JAVA_OPTIONS:  -Duser.home=/home/linuxbrew/.cache/Homebrew/java_cache
Exception in thread "main" java.lang.NullPointerException
</Long\ =\ 1000/> expected to be =~
<"2018-08-31 03:00:29 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable\n\nFailed to initialize compiler: object java.lang.Object in compiler mirror not found.
+ grep -qx Error: .*: failed test.log
```

**Comment by sjackman** [comment]
- `dextractor`: remove it
- `phyx`: that's a bug in Linuxbrew/brew. You can add `phyx` to the list of `brew linkage` errors to ignore in `docker.test.yml`
- `isl@0.18`: I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/9169 to fix this issue
- `meme`: I've opened PR https://github.com/brewsci/homebrew-bio/pull/407 to bump the revision
- `ropebwt2`: remove it
- `ruby`: add `ruby` to the list of `brew test` errors to ignore in `docker.test.yml`
- `bioperl`: I've opened PR https://github.com/brewsci/homebrew-bio/pull/410 to bump the revision
- `circos`: I've opened PR https://github.com/brewsci/homebrew-bio/pull/408 to bump the revision
- `repeatmasker`: I've opened PR https://github.com/brewsci/homebrew-bio/pull/409 to bump the revision
- `igv`: install both `jdk` and `jdk@8` and add `igv` to the list of `brew test` errors to ignore in `docker.test.yml`
- `apache-spark`: remove it

Thanks for the awesome and detailed bug report!
